from __future__ import annotations

import argparse
import csv
import sqlite3
from pathlib import Path


TABLE_EXPORT_ORDER = [
    "songs",
    "song_audio_features",
    "song_catalog_memberships",
    "song_sources",
    "song_versions",
    "section_occurrences",
]


def get_table_columns(connection: sqlite3.Connection, table_name: str) -> list[str]:
    rows = connection.execute(f"PRAGMA table_info({table_name})").fetchall()
    return [row[1] for row in rows]


def fetch_song_ids(connection: sqlite3.Connection, scope: str) -> list[int]:
    if scope == "all":
        rows = connection.execute("SELECT id FROM songs ORDER BY id").fetchall()
        return [int(row[0]) for row in rows]

    if scope == "worship":
        rows = connection.execute(
            """
            SELECT DISTINCT song_id
            FROM song_catalog_memberships
            WHERE catalog_name = 'worship_strict'
            ORDER BY song_id
            """
        ).fetchall()
        return [int(row[0]) for row in rows]

    rows = connection.execute(
        """
        SELECT DISTINCT song_id
        FROM song_catalog_memberships
        WHERE catalog_name IN ('worship_strict', 'broad_christian_worship')
        ORDER BY song_id
        """
    ).fetchall()
    return [int(row[0]) for row in rows]


def fetch_version_ids(connection: sqlite3.Connection, song_ids: list[int]) -> list[int]:
    if not song_ids:
        return []
    placeholders = ",".join("?" for _ in song_ids)
    rows = connection.execute(
        f"""
        SELECT id
        FROM song_versions
        WHERE song_id IN ({placeholders})
        ORDER BY id
        """,
        song_ids,
    ).fetchall()
    return [int(row[0]) for row in rows]


def write_table_csv(
    connection: sqlite3.Connection,
    table_name: str,
    output_path: Path,
    where_sql: str = "",
    where_params: tuple = (),
) -> int:
    columns = get_table_columns(connection, table_name)
    select_list = ", ".join(columns)
    query = f"SELECT {select_list} FROM {table_name}"
    if where_sql:
        query += f" WHERE {where_sql}"
    query += " ORDER BY 1"

    rows = connection.execute(query, where_params).fetchall()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(columns)
        writer.writerows(rows)
    return len(rows)


def write_import_instructions(output_dir: Path, scope: str, counts: dict[str, int]) -> None:
    path = output_dir / "README_IMPORT_ORDER.md"
    lines = [
        "# Supabase Import Bundle",
        "",
        f"Scope: `{scope}`",
        "",
        "Import these CSV files into Supabase in this order:",
        "",
        "1. `songs.csv`",
        "2. `song_audio_features.csv`",
        "3. `song_catalog_memberships.csv`",
        "4. `song_sources.csv`",
        "5. `song_versions.csv`",
        "6. `section_occurrences.csv`",
        "",
        "Current row counts:",
        "",
    ]
    for table_name in TABLE_EXPORT_ORDER:
        lines.append(f"- `{table_name}.csv`: {counts.get(table_name, 0):,}")
    lines.extend(
        [
            "",
            "Notes:",
            "- IDs are preserved from SQLite so foreign keys stay aligned.",
            "- Supabase identity columns were configured to `GENERATED BY DEFAULT`, so importing explicit IDs is allowed.",
            "- If you re-run imports, truncate child tables first to avoid duplicates.",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Export Supabase-ready CSV bundle from local Melodex SQLite.")
    parser.add_argument(
        "--db",
        default=str(project_root / "data" / "processed" / "melodex_phase1.sqlite"),
        help="Path to local SQLite database.",
    )
    parser.add_argument(
        "--output-dir",
        default=str(project_root / "data" / "processed" / "supabase_import_bundle"),
        help="Directory to write CSV exports.",
    )
    parser.add_argument(
        "--scope",
        choices=["worship_and_broad", "worship", "all"],
        default="worship_and_broad",
        help="Dataset scope to export.",
    )
    args = parser.parse_args()

    db_path = Path(args.db)
    output_dir = Path(args.output_dir)

    connection = sqlite3.connect(db_path)
    try:
        song_ids = fetch_song_ids(connection, args.scope)
        version_ids = fetch_version_ids(connection, song_ids)

        counts: dict[str, int] = {}
        if song_ids:
            song_placeholders = ",".join("?" for _ in song_ids)
            version_placeholders = ",".join("?" for _ in version_ids) if version_ids else ""

            counts["songs"] = write_table_csv(
                connection,
                "songs",
                output_dir / "songs.csv",
                where_sql=f"id IN ({song_placeholders})",
                where_params=tuple(song_ids),
            )
            counts["song_audio_features"] = write_table_csv(
                connection,
                "song_audio_features",
                output_dir / "song_audio_features.csv",
                where_sql=f"song_id IN ({song_placeholders})",
                where_params=tuple(song_ids),
            )
            counts["song_catalog_memberships"] = write_table_csv(
                connection,
                "song_catalog_memberships",
                output_dir / "song_catalog_memberships.csv",
                where_sql=f"song_id IN ({song_placeholders})",
                where_params=tuple(song_ids),
            )
            counts["song_sources"] = write_table_csv(
                connection,
                "song_sources",
                output_dir / "song_sources.csv",
                where_sql=f"song_id IN ({song_placeholders})",
                where_params=tuple(song_ids),
            )
            if version_ids:
                counts["song_versions"] = write_table_csv(
                    connection,
                    "song_versions",
                    output_dir / "song_versions.csv",
                    where_sql=f"id IN ({version_placeholders})",
                    where_params=tuple(version_ids),
                )
                counts["section_occurrences"] = write_table_csv(
                    connection,
                    "section_occurrences",
                    output_dir / "section_occurrences.csv",
                    where_sql=f"song_version_id IN ({version_placeholders})",
                    where_params=tuple(version_ids),
                )
            else:
                counts["song_versions"] = 0
                counts["section_occurrences"] = 0
        else:
            for table_name in TABLE_EXPORT_ORDER:
                counts[table_name] = write_table_csv(connection, table_name, output_dir / f"{table_name}.csv", "1 = 0")
    finally:
        connection.close()

    write_import_instructions(output_dir, args.scope, counts)

    print(f"Supabase import bundle written to: {output_dir}")
    for table_name in TABLE_EXPORT_ORDER:
        print(f"{table_name}: {counts.get(table_name, 0)}")


if __name__ == "__main__":
    main()
